### ISSUE TITLE
Theme for vaadin-combo-box

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-material-theme#7]
Styles from 2.0:

```css
:host {
  position: absolute;
        box-shadow: var(--shadow-elevation-2dp_-_box-shadow);
        background: #fff;
        border-radius: 0 0 2px 2px;
        top: 0;
        left: 0;
        pointer-events: auto;

        
        z-index: 200;
        overflow: hidden;
}

#scroller {
  overflow: auto;
        max-height: var(--vaadin-combo-box-overlay-max-height, 65vh);

        
        transform: translate3d(0, 0, 0);

        
        -webkit-overflow-scrolling: touch;
}

#selector {
  --iron-list-items-container_-_border-top:  8px solid transparent; --iron-list-items-container_-_border-bottom:  8px solid transparent;;
}

#selector vaadin-combo-box-item {
  cursor: pointer;
        padding: 13px 16px;
        color: var(--primary-text-color);
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
}

:host([opened][loading]) {
  display: block !important;
        height: 58px;
}

#selector:not([touch-device]) vaadin-combo-box-item:hover, #selector vaadin-combo-box-item[focused] {
  background: #eee;
}

#selector vaadin-combo-box-item[selected] {
  color: var(--primary-color);
}

#selector vaadin-combo-box-item[hidden] {
  display: none;
}
```
